plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.board'
version = '0.0.1-SNAPSHOT'
description = 'One_More_Project'

// 2. 자바 17 환경 설정
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

// 3. Lombok 컴파일러 설정
configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

// 4. 라이브러리를 다운로드할 중앙 저장소
repositories {
    mavenCentral()
}

// 5. 의존성(Libraries) 설정
dependencies {
    // 내부적으로 spring-web, spring-webmvc, tomcat 등을 모두 포함
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // 비동기 통신(RestClient)을 위해 필요한 WebFlux 스타터
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    // 파라미터 유효성 검증 라이브러리
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // API 문서화를 위한 Swagger 라이브러리 (spring 3.5.x 버전과 호환하려면 2.8.x 이상 버전으로 가능.)
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.4'
    // 코드 가독성을 위한 Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    // 개발 편의를 위한 핫 리로드(Hot Reload) 도구
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    //테스터
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

// 6. 테스트 실행 엔진 설정
tasks.named('test') {
    useJUnitPlatform()
}