server:
  port: 8080

spring:
  profiles:
    active: prod  # 학교에서 테스트할 때는 dev, 실제 연동할 때는 prod로 변경

  servlet: # 사용자가 올리는 사진 파일의 최대 크기를 설정
    multipart:
      max-file-size: 15MB
      max-request-size: 76MB

  # 데이터 소스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/one-more-db  # your_db_name을 실제 DB 이름으로 변경
    username: postgres                               # PostgreSQL 접속 계정 (예: postgres)
    password: 1234                           # PostgreSQL 접속 비밀번호
    driver-class-name: org.postgresql.Driver

  # JPA 설정 (Hibernate)
  jpa:
    hibernate:
      ddl-auto: none                                   # 'none'은 개발자가 직접 DDL 관리. 'update'는 개발 시 편의용.
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


ai-server:

  url: "http://192.168.22.54:8000"  # python fast api server

# Swagger 관련 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html    # 접속 경로를 http://localhost:8080/swagger-ui.html 로 설정
    groups-order: DESC        # API 그룹 표시 순서
    operations-sorter: method # API를 GET, POST 순서로 정렬
  api-docs:
    path: /api-docs           # API 명세서(JSON)가 나오는 경로