# Server Configuration
server.port=8080
spring.profiles.active=prod

# Servlet Multipart
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=76MB

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/one-more-db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# External AI Server (FastAPI ?)
ai-server.url=http://192.168.22.54:8000

# Swagger (SpringDoc OpenAPI)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.groups-order=DESC
springdoc.swagger-ui.operations-sorter=method
springdoc.api-docs.path=/api-docs

# Ollama Base URL
spring.ai.ollama.base-url=http://127.0.0.1:11434
spring.ai.ollama.embedding.options.model=bge-m3
